export const LOUDSPEAKER = [
    {
        id: 0,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 1,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 2,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 3,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 4,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 5,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 6,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 7,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 8,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg"
    },
    {
        id: 9,
        image: "http://www.aplusaudios.com/assets/uploads/showcase/medium/showcaseproduct2019-05-2871008188.jpg",
        category: "loudspeaker",
        name: "SB18-F1550 (4'' VOICE COIL/1550W)",
        nominalDiameter: "18''",
        ratedImpedance: "8",
        powerHandingCapacity: "1550w RMS",
        peakPowerHandingCapacity: "3100w PEAK",
        sensitivity: "95dB",
        frequencyRange: "Fs-2000hz",
        voiceCoilDiameter: "4''",
        voiceCoilMaterial: "Copper",
        numberOfLayer: "2",
        kindOfLayer: "inside/outside ",
        magnet: "220x110x30 Y35",
        basket: "Aluminium",
        weight: "15.4kg",
        featured: true
    }
];